### PR TITLE
Fixes prepend data being injected in other languages

### LINKED ISSUE #379: SCSS prependData should happen only when `lang="scss"` or `lang="sass"`
**Describe the bug**
Currently, when we have `prependData` option of `scss` preprocessor, the `lang` type of `<style>` is not being respected, the `prependData` are being injected ignoring the `lang` type. The `prependData` logic should be executed only when `lang="scss"` or `lang="sass"`.

**To Reproduce**
https://github.com/maykefreitas/svelte-preprocess-example

**Expected behavior**
The expected behavior would be to not inject `prependData` unless the `style` tag has `lang="scss"`.

**Information about your project:**

- svelte-preprocess version: latest

The cause of this bug is the fact that [this logic](https://github.com/sveltejs/svelte-preprocess/blob/main/src/processors/scss.ts#L26) should be executed after the `if` declaration, not before.

### PR DESCRIPTION
**Pull request by maykefreitas**
Closes #379

### CODE REVIEW

**Comment by kaisermann** [comment]
Hey, @maykefreitas 👋 

Thanks for the contribution! Can you also do this for the other processors such as `stylus`, `less` and `coffeescript`?

**Comment by maykefreitas** [comment]
hey @kaisermann, sure I can :)

**Comment by maykefreitas** [comment]
@kaisermann done ✅

**Review by kaisermann — APPROVED** [review]
Neat 👌

**Pull request merged**
