### PR TITLE
support for Svelte 4

### PR DESCRIPTION
**Pull request by benmccann**
It'd probably be nice to update this before Svelte 4 is released

### CODE REVIEW

**Comment by dummdidumm** [comment]
Oh shit lol, I did this already and released a new version but didn't push the changes https://www.npmjs.com/package/svelte-preprocess

**Comment by kaisermann** [comment]
> Oh shit lol, I did this already and released a new version but didn't push the changes https://www.npmjs.com/package/svelte-preprocess

We're good then 😅 ?
CleanShot 2023-06-06 at 17 17 22

**Comment by benmccann** [comment]
Well the changes still need to be pushed I believe whether that's Simon pushing his changes or this PR being merged

**Comment by kaisermann** [comment]
> Well the changes still need to be pushed I believe whether that's Simon pushing his changes or this PR being merged

Ahh, my brain read "publish" instead of "push". Let's wait for him then

**Comment by dummdidumm** [comment]
It's on npm already, so we don't need this PR. But yes I need to push the changes so the GitHub repo is in sync with what's on npm

**Pull request closed without merging**
