### PR TITLE
Coffee hack for label

### PR DESCRIPTION
**Pull request by gcxfd**
### Before submitting the PR, please make sure you do the following

- [x] It's really useful if your PR relates to an outstanding issue, so please reference it in your PR, or create an explanatory one for discussion. In many cases features are absent for a reason.
- [x] This message body should clearly illustrate what problems it solves. If there are related issues, remember to reference them.
- [x] Ideally, include a test that fails without this PR but passes with it. PRs will only be merged once they pass CI. (Remember to `npm run lint`!)

### Tests

- [x] Run the tests with `npm test` or `yarn test`

### CODE REVIEW

**Comment by gcxfd** [comment]
it work , i release a preview in @rmw/svelte-preprocess
```
yarn add  -D @rmw/svelte-preprocess @rmw/coffee-label-patch
```
but test can't pass , says can't found module , but I don't know how fix , typescript is to hard to use

**Comment by mrkishi** [comment]
It's awesome that you figured out how to get that syntax to work!

Unfortunately `svelte-preprocess` can't use a patched Coffeescript compiler as that could break otherwise legitimate users' code.

I'm sure people looking to use reactive statements would use your patch, though.

**Comment by gcxfd** [comment]
image
I modified the code so that the :label syntax is enabled only when the label:true argument is passed. So we don't break compile.
```
    svelte(
      preprocess: [
        sveltePreprocess(
          coffeescript: {
            label:true
            sourceMap: true
          }
          stylus: true
          pug: true
        )
      ]
    )
```

**Comment by kaisermann** [comment]
Thanks for the contribution and the idea! However, as @mrkishi said, 

> Unfortunately svelte-preprocess can't use a patched Coffeescript compiler, at least not by default, as that would be quite surprising for users and would require on-going maintenance to make sure nothing breaks as the compiler changes.

**Pull request closed without merging**
