### PR TITLE
(fix) fallback to empty string if there are no attributes

### LINKED ISSUE #396: From 4.9.0: Cannot read property 'split' of undefined
Upgrading from `4.8.0` to `4.9.0` I get this:

```
12:45:35 PM [vite] Internal server error: Cannot read property 'split' of undefined
  Plugin: vite-plugin-svelte
  File: C:/kit/src/routes/__error.svelte
      at Object.parseAttributes (C:\kit\node_modules\svelte-preprocess\dist\modules\markup.js:19:10)
      at getScriptContent (C:\kit\node_modules\svelte-preprocess\dist\transformers\typescript.js:47:38)
      at injectVarsToCode (C:\kit\node_modules\svelte-preprocess\dist\transformers\typescript.js:83:20)
      at mixedImportsTranspiler (C:\kit\node_modules\svelte-preprocess\dist\transformers\typescript.js:205:26)
      at transformer (C:\kit\node_modules\svelte-preprocess\dist\transformers\typescript.js:275:11)
      at Object.exports.transform (C:\kit\node_modules\svelte-preprocess\dist\autoProcess.js:37:12)
      at async C:\kit\node_modules\svelte-preprocess\dist\autoProcess.js:113:29
      at async script (C:\kit\node_modules\svelte-preprocess\dist\autoProcess.js:143:33)
      at async process_single_tag (file:///C:/kit/node_modules/svelte/compiler.mjs:31534:27)
      at async Promise.all (index 0)
Cannot read property 'split' of undefined
```

I'm using `SvelteKit@1.0.0-next.162`.

### PR DESCRIPTION
**Pull request by dummdidumm**
Fixes #396

### Before submitting the PR, please make sure you do the following

- [x] It's really useful if your PR relates to an outstanding issue, so please reference it in your PR, or create an explanatory one for discussion. In many cases features are absent for a reason.
- [x] This message body should clearly illustrate what problems it solves. If there are related issues, remember to reference them.
- [x] Ideally, include a test that fails without this PR but passes with it. PRs will only be merged once they pass CI. (Remember to `npm run lint`!)

### Tests

- [x] Run the tests with `npm test` or `yarn test`

### CODE REVIEW

**Review by kaisermann — APPROVED** [review]
🙏

**Comment by frederikhors** [comment]
There are many lint suggestions in this PR from Github.

**Comment by frederikhors** [comment]
image

**Comment by frederikhors** [comment]
image

**Comment by kaisermann** [comment]
@frederikhors Despite being in favour of both these rules (I put them in the project), the first is more of a nuisance and the second is just wrong for these respective cases. It's safe to ignore them 😁

**Pull request merged**
